const mongoose = require("mongoose");
const Job = require("./jobs");
require("dotenv").config();
const { v4: uuidv4 } = require("uuid");

const jobList = [
  {
    title: "Data Scientist",
    company: "Data Insights Corp",
    publishedDate: "2023-03-10",
    expireDate: "2023-04-30",
    experience: 4,
    description:
      "Analyze and interpret complex data sets to extract valuable insights.",
    requiredSkills: ["Python", "Machine Learning", "Data Visualization"],
    location: "Chicago, IL",
    salary: 100000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work schedule",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Master's degree in Data Science or related field",
    workMode: "Hybrid",
  },
  {
    title: "UX/UI Designer",
    company: "Creative Design Agency",
    publishedDate: "2023-04-15",
    expireDate: "2023-05-31",
    experience: 3,
    description:
      "Create intuitive and visually appealing user interfaces for web and mobile applications.",
    requiredSkills: ["UI/UX Design", "Sketch", "Figma"],
    location: "San Francisco, CA",
    salary: 95000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Design or related field",
    workMode: "Remote",
  },
  {
    title: "Financial Analyst",
    company: "Finance Solutions LLC",
    publishedDate: "2023-05-20",
    expireDate: "2023-06-30",
    experience: 3,
    description:
      "Analyze financial data and trends to provide insights and support decision-making.",
    requiredSkills: ["Financial Analysis", "Excel", "Budgeting"],
    location: "New York, NY",
    salary: 90000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Bachelor's degree in Finance or related field",
    workMode: "Office",
  },
  {
    title: "HR Specialist",
    company: "People Dynamics",
    publishedDate: "2023-06-10",
    expireDate: "2023-07-31",
    experience: 2,
    description:
      "Manage HR functions including recruitment, employee relations, and benefits.",
    requiredSkills: ["HR Management", "Recruitment", "Employee Relations"],
    location: "Denver, CO",
    salary: 70000,
    benefitsAndPerks: [
      "401(k) matching",
      "Flexible work hours",
      "Health insurance",
    ],
    industryType: "Startup",
    employmentType: "Trainee",
    education: "Bachelor's degree in Human Resources or related field",
    workMode: "Hybrid",
  },
  {
    title: "Network Engineer",
    company: "Networking Solutions Inc.",
    publishedDate: "2023-07-01",
    expireDate: "2023-08-31",
    experience: 4,
    description:
      "Design, implement, and manage secure and scalable network infrastructure.",
    requiredSkills: [
      "Cisco",
      "Routing and Switching",
      "Firewall Configuration",
    ],
    location: "Dallas, TX",
    salary: 80000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Computer Networking or related field",
    workMode: "Office",
  },
  {
    title: "Content Writer",
    company: "Content Creators Co.",
    publishedDate: "2023-08-15",
    expireDate: "2023-09-30",
    experience: 2,
    description:
      "Create engaging and SEO-friendly content for various digital platforms.",
    requiredSkills: ["Content Writing", "SEO", "Copywriting"],
    location: "Austin, TX",
    salary: 60000,
    benefitsAndPerks: [
      "Flexible work hours",
      "Health insurance",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Part-time",
    education: "Bachelor's degree in English, Journalism, or related field",
    workMode: "Remote",
  },
  {
    title: "Product Manager",
    company: "Tech Innovate",
    publishedDate: "2023-09-01",
    expireDate: "2023-10-31",
    experience: 5,
    description:
      "Lead product development and strategy to bring innovative products to market.",
    requiredSkills: ["Product Management", "Agile", "Market Analysis"],
    location: "Seattle, WA",
    salary: 110000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "Stock options",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Business or related field",
    workMode: "Hybrid",
  },
  {
    title: "Sales Representative",
    company: "Sales Dynamics Inc.",
    publishedDate: "2023-10-15",
    expireDate: "2023-11-30",
    experience: 2,
    description:
      "Build and maintain relationships with clients, and achieve sales targets.",
    requiredSkills: [
      "Sales",
      "Customer Relationship Management",
      "Negotiation",
    ],
    location: "Chicago, IL",
    salary: 60000,
    benefitsAndPerks: [
      "Uncapped commission",
      "Health insurance",
      "Professional development",
    ],
    industryType: "Corporate",
    employmentType: "Part-time",
    education: "Bachelor's degree in Business or related field",
    workMode: "Remote",
  },
  {
    title: "Quality Assurance Analyst",
    company: "Quality Tech Solutions",
    publishedDate: "2023-11-01",
    expireDate: "2023-12-31",
    experience: 3,
    description:
      "Ensure the quality of software products through rigorous testing procedures.",
    requiredSkills: ["Quality Assurance", "Testing", "Test Automation"],
    location: "Boston, MA",
    salary: 75000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Computer Science or related field",
    workMode: "Hybrid",
  },
  {
    title: "Graphic Designer",
    company: "Visual Arts Studio",
    publishedDate: "2023-12-15",
    expireDate: "2024-01-31",
    experience: 2,
    description:
      "Create visually stunning graphics and designs for various projects.",
    requiredSkills: ["Graphic Design", "Adobe Creative Suite", "Typography"],
    location: "Los Angeles, CA",
    salary: 70000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Graphic Design or related field",
    workMode: "Office",
  },
  {
    title: "Project Manager",
    company: "Project Management Experts",
    publishedDate: "2024-01-01",
    expireDate: "2024-02-28",
    experience: 5,
    description:
      "Lead and oversee project teams to ensure successful project delivery.",
    requiredSkills: ["Project Management", "Agile", "Team Leadership"],
    location: "New York, NY",
    salary: 100000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Project Management or related field",
    workMode: "Hybrid",
  },
  {
    title: "Customer Support Specialist",
    company: "Support Solutions Ltd.",
    publishedDate: "2024-02-15",
    expireDate: "2024-03-31",
    experience: 1,
    description:
      "Provide exceptional customer support to resolve inquiries and issues.",
    requiredSkills: ["Customer Service", "Communication", "Problem Solving"],
    location: "Austin, TX",
    salary: 50000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Part-time",
    education: "Associate's degree or equivalent experience",
    workMode: "Remote",
  },
  {
    title: "Systems Administrator",
    company: "IT Solutions Group",
    publishedDate: "2024-03-01",
    expireDate: "2024-04-30",
    experience: 3,
    description:
      "Manage and maintain the organization's computer systems and networks.",
    requiredSkills: ["System Administration", "Linux", "Networking"],
    location: "Seattle, WA",
    salary: 70000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Information Technology",
    workMode: "Hybrid",
  },
  {
    title: "Legal Counsel",
    company: "Legal Solutions LLC",
    publishedDate: "2024-04-15",
    expireDate: "2024-05-31",
    experience: 4,
    description:
      "Provide legal advice and support to ensure compliance with laws and regulations.",
    requiredSkills: ["Legal Research", "Contract Negotiation", "Legal Writing"],
    location: "Washington, D.C.",
    salary: 110000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "401(k) matching",
      "Flexible work hours",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Juris Doctor (JD) degree and Bar admission",
    workMode: "Office",
  },
  {
    title: "UX/UI Designer",
    company: "Design Innovations Co.",
    publishedDate: "2024-05-01",
    expireDate: "2024-06-30",
    experience: 3,
    description:
      "Design user interfaces and experiences for web and mobile applications.",
    requiredSkills: ["UI/UX Design", "Adobe XD", "Prototyping"],
    location: "San Francisco, CA",
    salary: 95000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Design or related field",
    workMode: "Remote",
  },
  {
    title: "Biomedical Engineer",
    company: "HealthTech Innovations",
    publishedDate: "2024-06-15",
    expireDate: "2024-07-31",
    experience: 2,
    description: "Design and develop medical devices and technologies.",
    requiredSkills: [
      "Biomedical Engineering",
      "Medical Device Design",
      "Biomechanics",
    ],
    location: "Boston, MA",
    salary: 80000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Biomedical Engineering",
    workMode: "Hybrid",
  },
  {
    title: "Environmental Scientist",
    company: "Eco Solutions Group",
    publishedDate: "2024-07-01",
    expireDate: "2024-08-31",
    experience: 3,
    description:
      "Conduct environmental research and assessments for sustainable practices.",
    requiredSkills: [
      "Environmental Science",
      "Data Analysis",
      "Environmental Impact Assessment",
    ],
    location: "Portland, OR",
    salary: 70000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Bachelor's degree in Environmental Science",
    workMode: "Office",
  },
  {
    title: "Cybersecurity Analyst",
    company: "SecureTech Solutions",
    publishedDate: "2024-08-15",
    expireDate: "2024-09-30",
    experience: 2,
    description: "Monitor and secure computer systems from cyber threats.",
    requiredSkills: [
      "Cybersecurity",
      "Firewall Configuration",
      "Incident Response",
    ],
    location: "Houston, TX",
    salary: 80000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Cybersecurity",
    workMode: "Remote",
  },
  {
    title: "AI/ML Engineer",
    company: "Innovative AI Solutions",
    publishedDate: "2024-10-15",
    expireDate: "2024-11-30",
    experience: 3,
    description:
      "Develop and implement machine learning models for advanced AI applications.",
    requiredSkills: ["Machine Learning", "Python", "TensorFlow"],
    location: "Seattle, WA",
    salary: 90000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Master's degree in Computer Science or related field",
    workMode: "Hybrid",
  },
  {
    title: "Civil Engineer",
    company: "Urban Development Group",
    publishedDate: "2024-11-01",
    expireDate: "2024-12-31",
    experience: 4,
    description:
      "Design and oversee construction projects, ensuring compliance with regulations.",
    requiredSkills: ["Civil Engineering", "AutoCAD", "Project Management"],
    location: "Los Angeles, CA",
    salary: 95000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Bachelor's degree in Civil Engineering",
    workMode: "Office",
  },
  {
    title: "Healthcare Administrator",
    company: "Health Systems Management",
    publishedDate: "2024-12-15",
    expireDate: "2025-01-31",
    experience: 5,
    description:
      "Manage healthcare facility operations, ensuring high-quality patient care.",
    requiredSkills: ["Healthcare Administration", "Budgeting", "Leadership"],
    location: "New York, NY",
    salary: 110000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Master's degree in Healthcare Administration or related field",
    workMode: "Hybrid",
  },
  {
    title: "E-commerce Specialist",
    company: "Online Retail Solutions",
    publishedDate: "2025-01-01",
    expireDate: "2025-02-28",
    experience: 3,
    description:
      "Optimize online sales strategies and manage e-commerce platforms.",
    requiredSkills: ["E-commerce", "Digital Marketing", "Analytics"],
    location: "San Francisco, CA",
    salary: 85000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Marketing or related field",
    workMode: "Remote",
  },
  {
    title: "Biotech Research Scientist",
    company: "Biotech Innovations Lab",
    publishedDate: "2025-02-15",
    expireDate: "2025-03-31",
    experience: 4,
    description:
      "Conduct research in biotechnology, contribute to scientific advancements.",
    requiredSkills: ["Biotechnology", "Genetic Engineering", "Lab Techniques"],
    location: "Boston, MA",
    salary: 100000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Ph.D. in Biotechnology or related field",
    workMode: "Hybrid",
  },
  {
    title: "Social Media Manager",
    company: "Digital Influence Agency",
    publishedDate: "2025-03-01",
    expireDate: "2025-04-30",
    experience: 3,
    description:
      "Develop and implement social media strategies to enhance brand visibility.",
    requiredSkills: ["Social Media Marketing", "Content Creation", "Analytics"],
    location: "Los Angeles, CA",
    salary: 80000,
    benefitsAndPerks: [
      "Health insurance",
      "401(k) matching",
      "Remote work options",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Bachelor's degree in Marketing or related field",
    workMode: "Remote",
  },
  {
    title: "Mechanical Engineer",
    company: "Engineering Solutions Inc.",
    publishedDate: "2025-04-15",
    expireDate: "2025-05-31",
    experience: 3,
    description:
      "Design and analyze mechanical systems and components for various projects.",
    requiredSkills: [
      "Mechanical Engineering",
      "CAD",
      "Finite Element Analysis",
    ],
    location: "Houston, TX",
    salary: 90000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Mechanical Engineering",
    workMode: "Office",
  },
  {
    title: "Digital Analyst",
    company: "Digital Insights Agency",
    publishedDate: "2025-05-01",
    expireDate: "2025-06-30",
    experience: 2,
    description:
      "Analyze digital marketing data to provide actionable insights and recommendations.",
    requiredSkills: [
      "Digital Analytics",
      "Data Visualization",
      "Google Analytics",
    ],
    location: "Chicago, IL",
    salary: 75000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Part-time",
    education: "Bachelor's degree in Business Analytics or related field",
    workMode: "Remote",
  },
  {
    title: "Mechatronics Engineer",
    company: "Automation Tech Solutions",
    publishedDate: "2025-06-15",
    expireDate: "2025-07-31",
    experience: 2,
    description:
      "Integrate mechanical and electronic systems to create automated solutions.",
    requiredSkills: ["Mechatronics", "PLC Programming", "Robotics"],
    location: "Seattle, WA",
    salary: 80000,
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Mechatronics Engineering",
    workMode: "Hybrid",
  },
  {
    title: "UX Researcher",
    company: "User Experience Insights",
    publishedDate: "2025-07-01",
    expireDate: "2025-08-31",
    experience: 3,
    description:
      "Conduct user research to inform and improve the design of digital products.",
    requiredSkills: ["UX Research", "Usability Testing", "User Interviews"],
    location: "San Francisco, CA",
    salary: 95000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Master's degree in Human-Computer Interaction or related field",
    workMode: "Remote",
  },
  {
    title: "Software Quality Assurance Engineer",
    company: "Quality Software Solutions",
    publishedDate: "2025-08-15",
    expireDate: "2025-09-30",
    experience: 2,
    description:
      "Ensure the quality of software products through testing and quality assurance processes.",
    requiredSkills: ["Quality Assurance", "Testing", "Test Automation"],
    location: "Austin, TX",
    salary: 70000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Part-time",
    education: "Bachelor's degree in Computer Science or related field",
    workMode: "Remote",
  },
  {
    title: "Digital Marketing Manager",
    company: "Digital Impact Solutions",
    publishedDate: "2025-09-01",
    expireDate: "2025-10-31",
    experience: 4,
    description:
      "Lead digital marketing strategies and campaigns to drive online visibility.",
    requiredSkills: ["Digital Marketing", "SEO", "Social Media Advertising"],
    location: "New York, NY",
    salary: 100000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Marketing or related field",
    workMode: "Hybrid",
  },
  {
    title: "Embedded Systems Engineer",
    company: "Embedded Tech Innovations",
    publishedDate: "2025-10-15",
    expireDate: "2025-11-30",
    experience: 3,
    description:
      "Design and develop embedded systems for various electronic devices.",
    requiredSkills: [
      "Embedded Systems",
      "C/C++",
      "Microcontroller Programming",
    ],
    location: "San Francisco, CA",
    salary: 90000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Electrical Engineering or related field",
    workMode: "Remote",
  },
  {
    title: "Health and Safety Officer",
    company: "Safety Solutions Ltd.",
    publishedDate: "2025-11-01",
    expireDate: "2025-12-31",
    experience: 2,
    description:
      "Implement and oversee health and safety programs to ensure a secure work environment.",
    requiredSkills: ["Health and Safety", "Risk Assessment", "Compliance"],
    location: "Seattle, WA",
    salary: 75000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education:
      "Bachelor's degree in Occupational Health and Safety or related field",
    workMode: "Hybrid",
  },
  {
    title: "AI Ethics Specialist",
    company: "Ethical AI Solutions",
    publishedDate: "2025-12-15",
    expireDate: "2026-01-31",
    experience: 3,
    description:
      "Ensure ethical considerations in the development and deployment of AI systems.",
    requiredSkills: ["AI Ethics", "Ethical AI Design", "Policy Development"],
    location: "Los Angeles, CA",
    salary: 95000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Corporate",
    employmentType: "Full-time",
    education: "Master's degree in Ethics, AI, or related field",
    workMode: "Remote",
  },
  {
    title: "Business Intelligence Analyst",
    company: "Insightful Analytics Group",
    publishedDate: "2026-01-01",
    expireDate: "2026-02-28",
    experience: 4,
    description:
      "Collect and analyze data to provide valuable insights for business decision-making.",
    requiredSkills: ["Business Intelligence", "Data Analysis", "SQL"],
    location: "Chicago, IL",
    salary: 100000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "401(k) matching",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Business Analytics or related field",
    workMode: "Hybrid",
  },
  {
    title: "DevOps Engineer",
    company: "DevOps Solutions Inc.",
    publishedDate: "2026-02-15",
    expireDate: "2026-03-31",
    experience: 3,
    description:
      "Implement and manage continuous integration and deployment pipelines.",
    requiredSkills: ["DevOps", "Docker", "CI/CD"],
    location: "Austin, TX",
    salary: 90000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Computer Science or related field",
    workMode: "Remote",
  },
  {
    title: "Clinical Research Coordinator",
    company: "Clinical Trials Institute",
    publishedDate: "2026-03-01",
    expireDate: "2026-04-30",
    experience: 2,
    description:
      "Coordinate and oversee clinical research studies in collaboration with medical teams.",
    requiredSkills: [
      "Clinical Research",
      "Project Management",
      "Regulatory Compliance",
    ],
    location: "Boston, MA",
    salary: 80000,
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Professional development",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Life Sciences or related field",
    workMode: "Hybrid",
  },
  {
    title: "Cloud Solutions Architect",
    company: "Cloud Innovations Tech",
    publishedDate: "2026-04-15",
    expireDate: "2026-05-31",
    experience: 4,
    description:
      "Design and implement scalable and secure cloud solutions for enterprise applications.",
    requiredSkills: ["Cloud Architecture", "AWS", "Azure"],
    location: "Seattle, WA",
    salary: 100000,
    benefitsAndPerks: [
      "Health insurance",
      "401(k) matching",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Computer Science or related field",
    workMode: "Hybrid",
  },
  {
    title: "Public Relations Specialist",
    company: "PR Strategies Group",
    publishedDate: "2026-05-01",
    expireDate: "2026-06-30",
    experience: 3,
    description:
      "Develop and implement PR campaigns to enhance the public image of the company.",
    requiredSkills: ["Public Relations", "Media Relations", "Communication"],
    location: "Los Angeles, CA",
    salary: 85000,
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "Startup",
    employmentType: "Full-time",
    education: "Bachelor's degree in Public Relations or related field",
    workMode: "Remote",
  },
  {
    title: "Data Engineer",
    company: "Data Engineering Solutions",
    publishedDate: "2026-06-15",
    expireDate: "2026-07-31",
    experience: 2,
    description:
      "Build and maintain scalable data infrastructure for efficient data processing.",
    requiredSkills: ["Data Engineering", "SQL", "Big Data Technologies"],
    location: "San Francisco, CA",
    salary: 90000,
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    industryType: "MNC",
    employmentType: "Full-time",
    education: "Bachelor's degree in Computer Science or related field",
    workMode: "Remote",
  },
];

mongoose.connect(process.env.DB_URI).then((res) => console.log("connected"));

// Promise.all(jobList.map((job) => Job.create({ jobId: uuidv4(), ...job }))).then(
//   (res) => console.log("done")
// );
