const DATA = [
  {
    id: 1,
    title: "Software Engineer",
    company: "Tech Innovators",
    publishedOn: "2023-01-15",
    experience: "3 years",
    expireDate: "2023-02-28",
    desc: "Join our innovative team to develop cutting-edge software solutions.",
    requiredSkills: ["JavaScript", "React", "Node.js", "MongoDB"],
    location: "San Francisco, CA",
    salary: "$90,000 - $110,000",
    benefitsAndPerks: [
      "Health insurance",
      "Stock options",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Computer Science",
  },
  {
    id: 2,
    title: "Marketing Specialist",
    company: "Digital Marketing Pro",
    publishedOn: "2023-02-01",
    experience: "2 years",
    expireDate: "2023-03-15",
    desc: "Drive successful digital marketing campaigns with our dynamic team.",
    requiredSkills: ["Social Media Marketing", "SEO", "Content Creation"],
    location: "New York, NY",
    salary: "$70,000 - $90,000",
    benefitsAndPerks: [
      "401(k) matching",
      "Flexible hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Marketing",
    employmentType: "Permanent",
    education: "Bachelor's degree in Marketing",
  },
  {
    id: 3,
    title: "Data Scientist",
    company: "Data Insights Corp",
    publishedOn: "2023-03-10",
    experience: "4 years",
    expireDate: "2023-04-30",
    desc: "Analyze and interpret complex data sets to extract valuable insights.",
    requiredSkills: ["Python", "Machine Learning", "Data Visualization"],
    location: "Chicago, IL",
    salary: "$100,000 - $120,000",
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work schedule",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Data Science",
    employmentType: "Permanent",
    education: "Master's degree in Data Science or related field",
  },
  {
    id: 4,
    title: "Graphic Designer",
    company: "Creative Designs Studio",
    publishedOn: "2023-04-05",
    experience: "2-3 years",
    expireDate: "2023-05-31",
    desc: "Create visually stunning designs for a variety of projects.",
    requiredSkills: ["Adobe Creative Suite", "UI/UX Design", "Illustration"],
    location: "Los Angeles, CA",
    salary: "$60,000 - $80,000",
    benefitsAndPerks: [
      "Flexible work hours",
      "Health insurance",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Design",
    employmentType: "Permanent",
    education: "Bachelor's degree in Graphic Design or related field",
  },
  {
    id: 5,
    title: "Product Manager",
    company: "Tech Innovate",
    publishedOn: "2023-05-20",
    experience: "5 years",
    expireDate: "2023-06-30",
    desc: "Lead product development and strategy to bring innovative products to market.",
    requiredSkills: ["Product Management", "Agile", "Market Analysis"],
    location: "Seattle, WA",
    salary: "$110,000 - $130,000",
    benefitsAndPerks: [
      "Health and dental coverage",
      "Stock options",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Business or related field",
  },
  {
    id: 6,
    title: "HR Specialist",
    company: "People Dynamics",
    publishedOn: "2023-06-10",
    experience: "2-4 years",
    expireDate: "2023-07-31",
    desc: "Manage HR functions including recruitment, employee relations, and benefits.",
    requiredSkills: ["HR Management", "Recruitment", "Employee Relations"],
    location: "Denver, CO",
    salary: "$70,000 - $90,000",
    benefitsAndPerks: [
      "401(k) matching",
      "Flexible work hours",
      "Health insurance",
    ],
    role: "Full-time",
    industryType: "Human Resources",
    employmentType: "Permanent",
    education: "Bachelor's degree in Human Resources or related field",
  },
  {
    id: 7,
    title: "Financial Analyst",
    company: "Finance Solutions LLC",
    publishedOn: "2023-07-15",
    experience: "3 years",
    expireDate: "2023-08-31",
    desc: "Analyze financial data and trends to provide insights and support decision-making.",
    requiredSkills: ["Financial Analysis", "Excel", "Budgeting"],
    location: "New York, NY",
    salary: "$80,000 - $100,000",
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Finance",
    employmentType: "Permanent",
    education: "Bachelor's degree in Finance or related field",
  },
  {
    id: 8,
    title: "UX/UI Designer",
    company: "Creative Design Agency",
    publishedOn: "2023-08-20",
    experience: "3-5 years",
    expireDate: "2023-09-30",
    desc: "Create intuitive and visually appealing user interfaces for web and mobile applications.",
    requiredSkills: ["UI/UX Design", "Sketch", "Figma"],
    location: "San Francisco, CA",
    salary: "$90,000 - $110,000",
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Design",
    employmentType: "Permanent",
    education: "Bachelor's degree in Design or related field",
  },
  {
    id: 9,
    title: "Network Engineer",
    company: "Networking Solutions Inc.",
    publishedOn: "2023-09-10",
    experience: "4 years",
    expireDate: "2023-10-31",
    desc: "Design, implement, and manage secure and scalable network infrastructure.",
    requiredSkills: [
      "Cisco",
      "Routing and Switching",
      "Firewall Configuration",
    ],
    location: "Dallas, TX",
    salary: "$80,000 - $100,000",
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Information Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Computer Networking or related field",
  },
  {
    id: 10,
    title: "Content Writer",
    company: "Content Creators Co.",
    publishedOn: "2023-10-05",
    experience: "2-3 years",
    expireDate: "2023-11-30",
    desc: "Create engaging and SEO-friendly content for various digital platforms.",
    requiredSkills: ["Content Writing", "SEO", "Copywriting"],
    location: "Austin, TX",
    salary: "$60,000 - $80,000",
    benefitsAndPerks: [
      "Flexible work hours",
      "Health insurance",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Content Creation",
    employmentType: "Permanent",
    education: "Bachelor's degree in English, Journalism, or related field",
  },
  {
    id: 11,
    title: "Systems Administrator",
    company: "IT Solutions Group",
    publishedOn: "2023-11-15",
    experience: "3-4 years",
    expireDate: "2023-12-31",
    desc: "Manage and maintain the organization's computer systems and networks.",
    requiredSkills: ["System Administration", "Linux", "Networking"],
    location: "Seattle, WA",
    salary: "$70,000 - $90,000",
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Information Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Information Technology",
  },
  {
    id: 12,
    title: "Sales Representative",
    company: "Sales Dynamics Inc.",
    publishedOn: "2023-12-01",
    experience: "2-3 years",
    expireDate: "2024-01-31",
    desc: "Build and maintain relationships with clients, and achieve sales targets.",
    requiredSkills: [
      "Sales",
      "Customer Relationship Management",
      "Negotiation",
    ],
    location: "Chicago, IL",
    salary: "$60,000 - $80,000",
    benefitsAndPerks: [
      "Uncapped commission",
      "Health insurance",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Sales",
    employmentType: "Permanent",
    education: "Bachelor's degree in Business or related field",
  },
  {
    id: 13,
    title: "Quality Assurance Analyst",
    company: "Quality Tech Solutions",
    publishedOn: "2024-01-15",
    experience: "2-4 years",
    expireDate: "2024-02-28",
    desc: "Ensure the quality of software products through rigorous testing procedures.",
    requiredSkills: ["Quality Assurance", "Testing", "Test Automation"],
    location: "Boston, MA",
    salary: "$75,000 - $95,000",
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Computer Science or related field",
  },
  {
    id: 14,
    title: "Customer Support Specialist",
    company: "Support Solutions Ltd.",
    publishedOn: "2024-02-10",
    experience: "1-2 years",
    expireDate: "2024-03-31",
    desc: "Provide exceptional customer support to resolve inquiries and issues.",
    requiredSkills: ["Customer Service", "Communication", "Problem Solving"],
    location: "Austin, TX",
    salary: "$50,000 - $70,000",
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Customer Support",
    employmentType: "Permanent",
    education: "Associate's degree or equivalent experience",
  },
  {
    id: 15,
    title: "Project Manager",
    company: "Project Management Experts",
    publishedOn: "2024-03-15",
    experience: "5 years",
    expireDate: "2024-04-30",
    desc: "Lead and oversee project teams to ensure successful project delivery.",
    requiredSkills: ["Project Management", "Agile", "Team Leadership"],
    location: "New York, NY",
    salary: "$100,000 - $120,000",
    benefitsAndPerks: [
      "Health coverage",
      "401(k) matching",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Project Management",
    employmentType: "Permanent",
    education: "Bachelor's degree in Project Management or related field",
  },
  {
    id: 16,
    title: "Frontend Developer",
    company: "Web Solutions Co.",
    publishedOn: "2024-04-10",
    experience: "3 years",
    expireDate: "2024-05-31",
    desc: "Design and implement user interfaces for web applications.",
    requiredSkills: ["HTML", "CSS", "JavaScript", "React"],
    location: "San Francisco, CA",
    salary: "$90,000 - $110,000",
    benefitsAndPerks: [
      "Health insurance",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Technology",
    employmentType: "Permanent",
    education: "Bachelor's degree in Computer Science or related field",
  },
  {
    id: 17,
    title: "Legal Counsel",
    company: "Legal Solutions LLC",
    publishedOn: "2024-05-20",
    experience: "4-6 years",
    expireDate: "2024-06-30",
    desc: "Provide legal advice and support to ensure compliance with laws and regulations.",
    requiredSkills: ["Legal Research", "Contract Negotiation", "Legal Writing"],
    location: "Washington, D.C.",
    salary: "$110,000 - $130,000",
    benefitsAndPerks: [
      "Health and dental coverage",
      "401(k) matching",
      "Flexible work hours",
    ],
    role: "Full-time",
    industryType: "Legal",
    employmentType: "Permanent",
    education: "Juris Doctor (JD) degree and Bar admission",
  },
  {
    id: 18,
    title: "Biomedical Engineer",
    company: "HealthTech Innovations",
    publishedOn: "2024-06-10",
    experience: "2-3 years",
    expireDate: "2024-07-31",
    desc: "Design and develop medical devices and equipment.",
    requiredSkills: [
      "Biomedical Engineering",
      "Medical Device Design",
      "Biomechanics",
    ],
    location: "Boston, MA",
    salary: "$80,000 - $100,000",
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Healthcare",
    employmentType: "Permanent",
    education: "Bachelor's degree in Biomedical Engineering or related field",
  },
  {
    id: 19,
    title: "Cybersecurity Analyst",
    company: "CyberGuard Solutions",
    publishedOn: "2024-07-15",
    experience: "2-4 years",
    expireDate: "2024-08-31",
    desc: "Monitor and secure computer systems and networks from cyber threats.",
    requiredSkills: [
      "Cybersecurity",
      "Firewall Configuration",
      "Incident Response",
    ],
    location: "Houston, TX",
    salary: "$80,000 - $100,000",
    benefitsAndPerks: [
      "Health and dental coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Cybersecurity",
    employmentType: "Permanent",
    education: "Bachelor's degree in Cybersecurity or related field",
  },
  {
    id: 20,
    title: "Environmental Scientist",
    company: "Eco Solutions Group",
    publishedOn: "2024-08-01",
    experience: "3-5 years",
    expireDate: "2024-09-30",
    desc: "Conduct environmental research and assessments to promote sustainable practices.",
    requiredSkills: [
      "Environmental Science",
      "Data Analysis",
      "Environmental Impact Assessment",
    ],
    location: "Portland, OR",
    salary: "$70,000 - $90,000",
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Professional development",
    ],
    role: "Full-time",
    industryType: "Environmental Science",
    employmentType: "Permanent",
    education: "Bachelor's degree in Environmental Science or related field",
  },
  {
    id: 21,
    title: "Supply Chain Manager",
    company: "Supply Chain Solutions Inc.",
    publishedOn: "2024-09-15",
    experience: "5 years",
    expireDate: "2024-10-31",
    desc: "Optimize and manage the end-to-end supply chain processes.",
    requiredSkills: [
      "Supply Chain Management",
      "Logistics",
      "Inventory Control",
    ],
    location: "Atlanta, GA",
    salary: "$100,000 - $120,000",
    benefitsAndPerks: [
      "Health and dental coverage",
      "401(k) matching",
      "Flexible work hours",
    ],
    role: "Full-time",
    industryType: "Supply Chain",
    employmentType: "Permanent",
    education: "Bachelor's degree in Business or related field",
  },
  {
    id: 22,
    title: "Pharmaceutical Researcher",
    company: "Pharma Innovations",
    publishedOn: "2024-10-10",
    experience: "2-3 years",
    expireDate: "2024-11-30",
    desc: "Conduct research and experiments to develop new pharmaceutical products.",
    requiredSkills: [
      "Pharmaceutical Research",
      "Laboratory Techniques",
      "Data Analysis",
    ],
    location: "San Diego, CA",
    salary: "$80,000 - $100,000",
    benefitsAndPerks: [
      "Health coverage",
      "Flexible work hours",
      "Remote work options",
    ],
    role: "Full-time",
    industryType: "Pharmaceuticals",
    employmentType: "Permanent",
    education: "Master's degree in Pharmaceutical Sciences or related field",
  },
];

exports.DATA = DATA;
